### ISSUE TITLE
setup.py fails with older versions of xmlsec1

### ISSUE THREAD

**Issue by winwinashwin** [xmlsec/python-xmlsec#281] opened 2024-01-16 10:46 UTC
When xmlsec1 version is pinned via env variable `PYXMLSEC_XMLSEC1_VERSION`, the [url resolution logic](https://github.com/xmlsec/python-xmlsec/blob/156394743a0c712e6638fe6e7e300c2f24b4fb12/setup.py#L328) returns `https://www.aleksey.com/xmlsec/download/xmlsec1-<pinned-version>.tar.gz` but this url is only valid for the latest version. 
Older versions seem to be at `https://www.aleksey.com/xmlsec/download/older-releases/`
The download is failing with 404: `Not Found`

**Comment by mxamin** [comment] 2024-04-18 09:19
Closing the issue because of being duplicate of https://github.com/xmlsec/python-xmlsec/issues/314

**Closed by mxamin** 2024-04-18 09:19 UTC
