### ISSUE TITLE
Issues with importing xmlsec.

### ISSUE THREAD

**Issue by asakapab0i** [xmlsec/python-xmlsec#317] opened 2024-04-18 07:16 UTC
Hi Team, 

It seems like we cannot import the xmlsec package because of this error.

Is there a matrix that we need to look into to make sure the xmlsec can be imported properly and we can install the right version on the system.

--
root@serv:/# pip freeze | grep lxml
lxml==5.2.1
root@serv:/# pip freeze | grep xmlsec
xmlsec==1.3.14

libxml2 version
--
libxml2/now 2.9.13+dfsg-1ubuntu0.4 arm64 [installed,local]
xmlsec1/now 1.2.33-1build2 arm64 [installed,local]

Here's the error I get when importing it
--
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import xmlsec
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
xmlsec.InternalError: (-1, 'lxml & xmlsec libxml2 library version mismatch')
>>>
KeyboardInterrupt
>>>

**Comment by mxamin** [comment] 2024-04-18 09:16
Closing it because of being duplicate of https://github.com/xmlsec/python-xmlsec/issues/316. 
Let's continue there :)

**Closed by mxamin** 2024-04-18 09:16 UTC
